# Generated by Django 5.2 on 2025-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casamento", "0002_convidado"),
    ]

    operations = [
        migrations.AddField(
            model_name="convidado",
            name="confirmado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="convidado",
            name="confirmado_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="convidado",
            name="senha",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
