# Generated by Django 5.2 on 2025-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casamento", "0003_convidado_confirmado_convidado_confirmado_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listapresente",
            name="pix_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
