# Generated by Django 5.2 on 2025-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casamento", "0004_listapresente_pix_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convidado",
            name="senha",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
