# Generated by Django 5.2 on 2025-05-15 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casamento", "0005_alter_convidado_senha"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembroDaFamilia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("confirmado", models.BooleanField(default=False)),
                (
                    "convidado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familia",
                        to="casamento.convidado",
                    ),
                ),
            ],
        ),
    ]
